In [70]:
#Numpy:: It is a python package, NUUMPERICAL PYTHON.
#2005 BY TRAVIS
#USES::
1. mathematical and logical calculations on array.
2. Built-in functions for linear algebra, random number generation.
3. used for scientific calc
4.faster than list

5.fast because associated to c


SyntaxError: invalid decimal literal (974652631.py, line 7)

In [1]:
#NUMPY IS OFTEN CALLED AS AN ALTERNATIVE FOR MATLAB.

In [2]:
#NUMPY IS USED WITH PACKAGES LIKE SCIPY(SCIENTIFIC PYTHON) AND MATPLOTLIB(PLOTTING LIBARARY) AND THUS MAKES IT CAPABLE TO REPLACE MATLAB.

In [9]:
# 1-D ARRAY : VECTOR
#2-D ARRAY : MATRIX
#3-D ARRAY : TENSOR   


In [28]:
#creating 1-d array:: VECTOR
import numpy as np
a=[1,2,3,4,5]
my_arr=np.array(a)
print(my_arr)

#also by 
import numpy as np
my_arr=np.array([1,2,3,4,5])
print(my_arr)

a=[]
length=int(input("enter the length of the array: "))
for i in range(length):
    el=int(input("enter the elements: "))
    a.append(el)

b=np.array(a)
print(b)
print(type(b))

    


[1 2 3 4 5]
[1 2 3 4 5]


enter the length of the array:  1
enter the elements:  1


[1]
<class 'numpy.ndarray'>


In [33]:
#creating 2-d array:: MATRIX
import numpy as np
a=[[1,2,3],[4,5,6],[1,2,3]]
my_arr=np.array(a)
print(my_arr)

#also by 
import numpy as np
my_arr=np.array([[1,2,3],[4,5,6],[1,2,3]])
print(my_arr)

 

print("MY DIMENSIONS: ",my_arr.ndim)                                      #to check dimesnion
print("SHAPE: ",my_arr.shape)                                             #to check shape

                                  

a=[]
length=int(input("enter the length of the array: "))##
for i in range(length):
    
    el=int(input("enter the elements: "))
    a.append(el)

b=np.array(a)
print(b)
print(type(b))

    


[[1 2 3]
 [4 5 6]
 [1 2 3]]
[[1 2 3]
 [4 5 6]
 [1 2 3]]
MY DIMENSIONS:  2
SHAPE:  (3, 3)


enter the length of the array:  2
enter the elements:  2
enter the elements:  2


[2 2]
<class 'numpy.ndarray'>


In [10]:
#NUMPY FUNCTIONS::
#1. ZEROES:: CREATES A 1-D OR 2-D ARRAY AND FILLS IT WITH ZERO

import numpy as np
arr = np.zeros(5)
print(arr)

arr = np.zeros((2,2))     #for 2-d input in form of tuple
print(arr)


#ones: 
import numpy as np
arr = np.ones(5)
print(arr)


arr = np.ones((2,2))     #for 2-d input in form of tuple
print(arr)

arr=np.full((3,3),10)    #for creating a array with a same number , 10 here
arr

arr=np.arange(10,21)
arr

arr=np.arange(10,20,2)  #with skip value
arr

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


array([10, 12, 14, 16, 18])

In [43]:
#3. EYE:: CREATES AS ALL THE DIAGONAL ELEMENTS AS 1 AND REST 0

import numpy as np
arr = np.eye(3)
print(arr)

arr = np.eye(2,1)   #here you need not to pass tuple and pass two diff arguments , if passed one it will build a square matrix

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1.]
 [0.]]


In [46]:
#4. DIAG :: ASSIGN THE GIVEN VALUE TO ALL THE DIAGONAL ELEMENTS AND REST AS 0
import numpy as np
arr = np.diag([1,2,3,4,8])
print(arr)
 #here the values would be given in a list and it will create a square matrix


#you can also use diag to extract all the diagonal elemnts  of a given array
print(np.diag(arr))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 8]]
[1 2 3 4 8]


In [72]:
#5. randint :: generate random numbers between a given range
# rand(min,max,total_values),        min=start,max=uptill, total=how many numbers you wanna generate between them

import numpy as np
arr=np.random.randint(1,10,3)
print(arr)

[9 3 4]


In [3]:
#6 rand: use to generate random value between 0 to 1
# syntax: rand(no. of values)
import numpy as num
arr=np.random.rand(2,)
print(arr)
import numpy as num
arr=np.random.rand(2,2)
print(arr)

NameError: name 'np' is not defined

In [60]:
#7. randn : use to generate a random value close to 0.This may return positive or negative value.

import numpy as np
arr=np.random.randn(2)
print(arr)
arr=np.random.randn(2,2)
print(arr)

[-0.32192674  0.59795737]
[[-1.45422391 -0.72895274]
 [-1.42878558  1.12296749]]


In [60]:
#7. randn : use to generate a random value close to 0.This may return positive or negative value.

import numpy as np
arr=np.random.randn(2)
print(arr)
arr=np.random.randn(2,2)
print(arr)

[-0.32192674  0.59795737]
[[-1.45422391 -0.72895274]
 [-1.42878558  1.12296749]]


In [104]:
#to print an array within a range

arr=np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [1]:
#SLICING 
#1-D ::

import numpy as np
list1=[]
a=int(input("enter the length of the array : "))
for i in range(a):
    el=int(input("enter the elements: "))
    list1.append(el)

arr=np.array(list1)
print(arr)

for i in range(arr.size):
    print(arr[(arr.size)-i-1])

enter the length of the array :  4
enter the elements:  4
enter the elements:  3
enter the elements:  2
enter the elements:  1


[4 3 2 1]
1
2
3
4


In [10]:
import numpy as np
list1=[]
a=int(input("enter the length of the array : "))
for i in range(a):
    el=int(input("enter the elements: "))
    list1.append(el)

arr=np.array(list1)
print(arr)

sum=0
for i in range(arr.size):
    sum+=arr[i]
    
print(sum)



enter the length of the array :  4
enter the elements:  4
enter the elements:  3
enter the elements:  2
enter the elements:  1


[4 3 2 1]
10


In [12]:
arr1=arr[2:4]
print(arr1)

[2 1]


In [18]:
#reshaping of 1-d array ::

import numpy as np
arr1=np.random.randint(0,50,12)
print(arr1)

arr1=arr1.reshape(2,6)    #reshaped with rows and colums, multiplication should be equal to total of elemenets
print(arr1)

#doing vice versa

arr1=arr1.reshape(12)
print(arr1)

[28  1  2 32 35 25 27 34 43 13 25  5]
[[28  1  2 32 35 25]
 [27 34 43 13 25  5]]
[28  1  2 32 35 25 27 34 43 13 25  5]


In [21]:
#to converting into 3d
arr1=arr1.reshape(2,2,3)
print(arr1)
print(arr1.ndim)

[[[28  1  2]
  [32 35 25]]

 [[27 34 43]
  [13 25  5]]]
3


In [31]:
import numpy as np
arr=np.random.randint(1,100,12)
print(arr)

arr=arr.reshape(4,3)
print(arr)

arr=arr.reshape(4,-1)                           #-1 menas that you have given the system to choose the input, (auto calculation)
print(arr)
arr=arr.reshape(-1,3)
print(arr)
arr=arr.reshape(-1,-1)                #you can only define one unspecified dimension
print(arr)

arr=arr.reshape(12)
print(arr)

arr=arr.reshape(2,2,3)
print(arr)

[37 33 22 71  5 77 46 88 65 91 51 39]
[[37 33 22]
 [71  5 77]
 [46 88 65]
 [91 51 39]]
[[37 33 22]
 [71  5 77]
 [46 88 65]
 [91 51 39]]
[[37 33 22]
 [71  5 77]
 [46 88 65]
 [91 51 39]]


ValueError: can only specify one unknown dimension

In [41]:
#SEED FUNCTION::
#WORKS SIMILAR TO TO randint function BUT HERE IT FIXES THE GENERATION OF THE RANDOM NUMBER, i.e fix set of random numbers 
import numpy as num
np.random.seed(1)
arr1=np.random.randint(1,100,12)
print(arr1)
arr1=np.random.randint(1,100,12)
print(arr1)

arr1=np.random.randint(1,100,14)
print(arr1)

arr1=np.random.randint(1,100,6)
print(arr1)



[38 13 73 10 76  6 80 65 17  2 77 72]
[ 7 26 51 21 19 85 12 29 30 15 51 69]
[88 88 95 97 87 14 10  8 64 62 23 58  2  1]
[61 82  9 89 14 48]


In [47]:
#2-d array:: ALSO KNOWN AS MATRIX  
#[[0,0],[0,1],[0,2]                   ROW,COL
# [1,0],[1,1],[1,2]]

#INDEXING:: array[ROW][COL]  ::: this is double bracket  notation 
# array[r,c]:: single bracket notation

# creating a 2-d array::matrix

import numpy as np
row=int(input("enter the number of rows: "))
col=int(input("enter the number of columns: "))

matrix=[]
for i in range(row):
    lis=[]
    for j in range(col):
        el=int(input(f"enter the element for element[{i},{j}]:: "))
        lis.append(el)

    matrix.append(lis)

print(matrix)
arr=np.array(matrix)
print(arr)
print(type(arr))
print(arr.size)



        


enter the number of rows:  2
enter the number of columns:  2
enter the element for element[0,0]::  1
enter the element for element[0,1]::  2
enter the element for element[1,0]::  3
enter the element for element[1,1]::  4


[[1, 2], [3, 4]]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
4


In [54]:
#Slicing:: 2-d array :: matrix
#syntax:: array_name[row range,column range]

import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,80]])


print(a[0:2,1:3])
print(a[1:2])
print(a[2:1])
print(a[2:])

[[20 30]
 [50 60]]
[[40 50 60]]
[]
[[70 80 80]]


In [14]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(1,500,30)
arr=arr.reshape(6,5)

#also  arr=np.random.randint(1,500,30).reshape(6,5) for a single line of code


print(arr)


[[ 38 236 397  73 256]
 [394 204 134 336 449]
 [145 130 461  72 238]
 [391 282 179 277 255]
 [358 403 469 396 253]
 [491 157 414 399  51]]


In [21]:
print(arr[2:2,4:4])


[]


In [24]:
## VIEW VS COPY :: WHEN WE SLICE A SUB ARRAY FROM AN ARRAY, IT MAY BE DONE BY TWO WAYS. 
#FIRST BY MAKING A VIEW AND THE SECOND IS COPY
#VIEW:: BY DEFALUT VIEW HAPPENS, HERE IF WE MAKE ANY CHANGES TO THE SUB ARRAY IT WILL ALSO REFLECT TO THE ORIGNAL ARRAY.
#COPY:: NO CHANGES WOULD BE REFLECTED ON THE ORIGNAL ARRAY

import numpy as np

a=np.array([1,2,3,4,5,6,7,8])
sliced=a[3:7]
sliced[:]=0                   # we updated the elements to zero and these would be reflected in orignal array by default
print(a)


a=np.array([1,2,3,4,5,6,7,8])
sliced=a[3:7].copy()
sliced[:]=0
print(a)




[1 2 3 0 0 0 0 8]
[1 2 3 4 5 6 7 8]


In [53]:
#CONDITIONAL SELECTION ::
import numpy as np
arr=np.arange(1,16)           #use to create a array directly 

print(arr>10)

#condition bases statements::
b=arr>10
print(arr[b])

c=arr<5
print(arr[c])

arr[arr%2==0]=22
print(arr)


arr[arr>11]=0
print(arr)




[False False False False False False False False False False  True  True
  True  True  True]
[11 12 13 14 15]
[1 2 3 4]
[ 1 22  3 22  5 22  7 22  9 22 11 22 13 22 15]
[ 1  0  3  0  5  0  7  0  9  0 11  0  0  0  0]


In [75]:
#NUMPY ARRAY OPERATIONS:: 
import math
import numpy as np
arr=np.arange(1,16)
print(arr)

print(arr*2)

arr=arr+2
print(arr)

arr=arr*2                     #here operation is done on the saved value
print(arr)

arr=np.arange(1,16)
arr=arr**2
print(arr)

arr=np.sqrt(arr)         #we have to use np (numpy) to calculate sqaure root
print(arr)

#arr=arr/0
#print(arr)   #in numpy when we divide by zero it retuend infinity and not an error 


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 6  8 10 12 14 16 18 20 22 24 26 28 30 32 34]
[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [82]:
arr1=np.arange(1,16)
arr2=np.arange(1,16)
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1-arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [94]:
#operations:: in a matric(2-d array)

import numpy as np
arr1=np.random.randint(1,100,9).reshape(3,3)
arr2=np.random.randint(1,100,9).reshape(3,3)
print(arr1)
print(arr2)


[[26 99 88]
 [ 8 27 26]
 [23 10 68]]
[[24 28 38]
 [58 84 39]
 [ 9 33 35]]


In [86]:
print(arr1+arr2)

[[ 90  73]
 [151  37]
 [106  75]
 [ 32 133]]


In [87]:
print(arr1-arr2)

[[-74  55]
 [-27   9]
 [ 10 -71]
 [-30 -11]]


In [96]:
print(arr1*arr2)        #to multiply elem1 to elem1 of mat of 2
print(arr1.dot(arr2))   #actual matrix amultiplcation


[[ 624 2772 3344]
 [ 464 2268 1014]
 [ 207  330 2380]]
[[ 7158 11948  7929]
 [ 1992  3350  2267]
 [ 1744  3728  3644]]


In [95]:
print(arr1/arr2)

[[1.08333333 3.53571429 2.31578947]
 [0.13793103 0.32142857 0.66666667]
 [2.55555556 0.3030303  1.94285714]]


In [15]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))   #index of min value
print(np.argmax(arr))
print(np.sqrt(arr[3]))
print(np.sin(arr))     #to get the sin value
print(np.cos(arr))
print(np.tan(arr))
print((np.sin(arr)/np.cos(arr)))

1
9
0
8
2.0
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566]


In [18]:
#linspace func:: 
# np.linspace(start,end,number of values)
#this function gives number of value between start and end with equal diff in between
arr=np.linspace(1,10,10)
print(arr)
arr=np.linspace(1,2,5)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1.   1.25 1.5  1.75 2.  ]


In [34]:
#for 2d matrix
#almost same to 1d (vector)
import numpy as np
np.random.seed(1)
matrix=np.random.randint(1,20,9).reshape(3,3)

print(matrix)
print(type(matrix))

print(np.sum(matrix))
print(np.min(matrix))
print(np.max(matrix))


print("sum",np.sum(matrix,axis=1))     #one denotes row
print("min for col ",np.min(matrix,axis=0))     #0 for colum
print("max for row ",np.max(matrix,axis=1))     



#to calculate cummilative sum
print(np.cumsum(matrix))      




[[ 6 12 13]
 [ 9 10 12]
 [ 6 16  1]]
<class 'numpy.ndarray'>
85
1
16
sum [31 31 23]
min for col  [ 6 10  1]
max for row  [13 12 16]
[ 6 18 31 40 50 62 68 84 85]


In [44]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(1,20,10)
print(arr)


#SHUFFLE FUNCTION :: THIS IS USED TO CHANGE THE POSITIONS OF THE ARRAY, ELEMENTS WONT CHANGE BUT THERE POSITIONS WOULD
np.random.shuffle(arr)
print(arr)


#UNIQUE:: GIVES ALL THE UNIQUE ELEMENTS AS THE OUTPUT, REMOVES THE DUPLICATE ARRAY
arr2=np.unique(arr)
print(arr2)
print(arr)


#YOU CAN ALSO GET SPECIFIED INDEX OF THE UNIQE VALUE AND ALSO GIVES THE FREQUENCY OF REPETATION
arr=np.unique(arr,return_index=True,return_counts=True)
print(arr)


[ 6 12 13  9 10 12  6 16  1 17]
[ 9  1  6  6 13 17 10 12 16 12]
[ 1  6  9 10 12 13 16 17]
[ 9  1  6  6 13 17 10 12 16 12]
(array([ 1,  6,  9, 10, 12, 13, 16, 17]), array([1, 2, 0, 6, 7, 4, 8, 5], dtype=int64), array([1, 2, 1, 1, 2, 1, 1, 1], dtype=int64))


In [49]:
# Stacking:: 

import numpy as np
arr1=np.array([10,20,30,40,50,60,70,80])
arr2=np.array([1,2,3,4,5,6,7,8])
print(arr1)
print(arr2)




#horizontal stack: np.hstack(arr1,arr2) , basically stacks the arrays horizontaly
print(np.hstack((arr1,arr2)))

#Vertical :: np.vstack(arr1,arr2) , basically stacks the arrays in vertically
print(np.vstack((arr1,arr2)))





[10 20 30 40 50 60 70 80]
[1 2 3 4 5 6 7 8]
[10 20 30 40 50 60 70 80  1  2  3  4  5  6  7  8]
[[10 20 30 40 50 60 70 80]
 [ 1  2  3  4  5  6  7  8]]


In [52]:
# Stacking::  for 2d rray(matrix)
import numpy as np
arr1=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
arr2=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(arr1)
print(arr2)



#horizontal stack: np.hstack(arr1,arr2) , basically stacks the arrays horizontaly
print(np.hstack((arr1,arr2)))


#Vertical :: np.vstack(arr1,arr2) , basically stacks the arrays in vertically
print(np.vstack((arr1,arr2)))







[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30  1  2  3]
 [40 50 60  4  5  6]
 [70 80 90  7  8  9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [62]:
a=np.array([1,2,3,4,5,6]).reshape(2,3)
b=np.random.randint(1,10,6).reshape(2,3)
print(a)
print(b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[[5 6 4]
 [7 9 1]]
[[1 2 3]
 [4 5 6]
 [5 6 4]
 [7 9 1]]
[[1 2 3 5 6 4]
 [4 5 6 7 9 1]]


In [106]:
import numpy as np
arr=np.array([0,1,2,3,5,6])
print(arr)

arr2=np.random.randint(1,20,10)
print(arr2)
arr2=np.arange(10,20)            #to print within a range
print(arr2)                  
 
#to print 5 , 10 times

arr=np.ones(10)*5
arr

[0 1 2 3 5 6]
[ 9 12 13 12  5  8  8 14  5 17]
[10 11 12 13 14 15 16 17 18 19]


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [85]:
#creating a 1-d array and convert it into 3*3 matrix
import numpy as np
arr=np.random.randint(1,20,9)
print(arr)

arr=arr.reshape(3,3)

print(arr)


[ 1 11 11  3  3 18  5  1 15]
[[ 1 11 11]
 [ 3  3 18]
 [ 5  1 15]]


In [95]:
#creating and converting all even numbers to 0
import numpy as np
np.random.seed(1)
arr=np.random.randint(1,20,15)
print(arr)

arr[arr%2==0]=0
print(arr)


[ 6 12 13  9 10 12  6 16  1 17  2 13  8 14  7]
[ 0  0 13  9  0  0  0  0  1 17  0 13  0  0  7]


In [100]:
#creating a 2-d array 3*3 but elements between 0-1
import numpy as np
arr=np.random.rand(3,3)
arr


array([[0.31551563, 0.68650093, 0.83462567],
       [0.01828828, 0.75014431, 0.98886109],
       [0.74816565, 0.28044399, 0.78927933]])

In [123]:
import numpy as np
arr=np.arange(1,17).reshape(4,4)
print(arr)
print(arr[1:,1:3])   #r:r,c:c


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 6  7]
 [10 11]
 [14 15]]


In [124]:
#NUMPY VS LIST::

#NUMPY :
1.SIZE: NUMPY DATA STRUCTURES TAKES LESS SPACE
2.PERFORMANCE: THEY HAVE ANEED FOR SPEED AND FASTER THAN LISTS
3. FUNTIONALITY : HAVE FUCNTIONS SUCH AS OPERATIONS BUILT IN


SyntaxError: invalid decimal literal (3487892309.py, line 4)

In [131]:
#PROOF::

# %timeit,  for single line
#%%timeit for multiple line code

%timeit [i**2 for i in range(1, 11)]
%timeit np.arange(1, 11)**2

1.92 µs ± 275 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
2.32 µs ± 36 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [137]:
#searching an element in numpy
#where() function:

import numpy as np
arr=np.arange(1,10)
x=np.where(arr==4)
print(x)

import numpy as np
arr=np.array([1,2,3,4,4,4,4,4,5,6,7,8])
x=np.where(arr==4)
print(x)
import numpy as np
arr=np.array([1,2,3,4,4,4,4,4,5,6,7,8])
x=np.where(arr%2==1)
print(x)

(array([3], dtype=int64),)
(array([3, 4, 5, 6, 7], dtype=int64),)
(array([ 0,  2,  8, 10], dtype=int64),)


In [145]:
#search sorted ()::

import numpy as np
a=np.array([4,3,5,2,3,1,4,5,3,57,90,34])
print(a)

arr=np.searchsorted(a,5)
print(arr)
print(a)
print(arr)

arr=np.searchsorted(a,5,side='right')        #to start searh from right side
print(arr)
print(a)
print(arr)


[ 4  3  5  2  3  1  4  5  3 57 90 34]
9
[ 4  3  5  2  3  1  4  5  3 57 90 34]
9
9
[ 4  3  5  2  3  1  4  5  3 57 90 34]
9
